### ISSUE TITLE
General error during conversion: Unsupported class file major version 64

### ISSUE THREAD

**Issue by prc992** [askimed/nf-test#152]
I'm getting a error using following the tutorial : 
https://code.askimed.com/nf-test/docs/testcases/nextflow_pipeline/

**The Error :** 

_Error: Syntax errors in nf-test config file: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Unsupported class file major version 64

java.lang.IllegalArgumentException: Unsupported class file major version 64
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:199)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:180)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:287)
	at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
	at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
	at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
	at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
	at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClassNullable(AsmReferenceResolver.java:57)
	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClass(AsmReferenceResolver.java:44)
	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveNonArrayType(AsmReferenceResolver.java:79)
	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveType(AsmReferenceResolver.java:70)
	at org.codehaus.groovy.ast.decompiled.MemberSignatureParser.createMethodNode(MemberSignatureParser.java:58)
	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.lambda$createMethodNode$1(DecompiledClassNode.java:230)
	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.createMethodNode(DecompiledClassNode.java:236)
	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.lazyInitMembers(DecompiledClassNode.java:203)
	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.getDeclaredMethods(DecompiledClassNode.java:122)
	at org.codehaus.groovy.ast.ClassNode.getDeclaredMethods(ClassNode.java:850)
	at org.codehaus.groovy.ast.ClassNode.getMethods(ClassNode.java:865)
	at org.apache.groovy.ast.tools.ClassNodeUtils.hasPossibleStaticMethod(ClassNodeUtils.java:243)
	at org.codehaus.groovy.ast.ClassNode.hasPossibleStaticMethod(ClassNode.java:1344)
	at org.codehaus.groovy.control.StaticImportVisitor.findStaticMethod(StaticImportVisitor.java:561)
	at org.codehaus.groovy.control.StaticImportVisitor.findStaticMethodImportFromModule(StaticImportVisitor.java:469)
	at org.codehaus.groovy.control.StaticImportVisitor.transformMethodCallExpression(StaticImportVisitor.java:252)
	at org.codehaus.groovy.control.StaticImportVisitor.transform(StaticImportVisitor.java:133)
	at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitExpressionStatement(ClassCodeExpressionTransformer.java:108)
	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:86)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitBlockStatement(ClassCodeVisitorSupport.java:164)
	at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:138)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:111)
	at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitConstructorOrMethod(ClassCodeExpressionTransformer.java:66)
	at org.codehaus.groovy.control.StaticImportVisitor.visitConstructorOrMethod(StaticImportVisitor.java:108)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitMethod(ClassCodeVisitorSupport.java:106)
	at org.codehaus.groovy.ast.ClassNode.visitMethods(ClassNode.java:1099)
	at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1092)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:52)
	at org.codehaus.groovy.control.CompilationUnit.lambda$addPhaseOperations$3(CompilationUnit.java:209)
	at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:942)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:671)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:635)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
	at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:526)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:538)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:426)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:470)
	at com.askimed.nf.test.config.Config.parse(Config.java:178)
	at com.askimed.nf.test.commands.RunTestsCommand.execute(RunTestsCommand.java:106)
	at com.askimed.nf.test.commands.AbstractCommand.call(AbstractCommand.java:41)
	at com.askimed.nf.test.commands.AbstractCommand.call(AbstractCommand.java:17)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.askimed.nf.test.App.run(App.java:44)
	at com.askimed.nf.test.App.main(App.java:51)

1 error_

**Software versions :** 

JAVA
_java version "20.0.1" 2023-04-18
Java(TM) SE Runtime Environment (build 20.0.1+9-29)
Java HotSpot(TM) 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)_

N E X T F L O W
version 23.10.0 build 5889

The computer and OS : 

Macbook pro with Apple M2 Pro with MacOs Ventura 13.4.1 (c)

Is this a know error or incompatibility with the current version?

**Comment by BrianSanderson** [comment]
I ran into the same issue on an HPC running **CentOS 7.9.2009** with **Java 20.0.2** and **Nextflow 23.04.3**, and [based on this discussion on the Nextflow slack](https://nextflow.slack.com/archives/C049MBCEW06/p1698750261086539?thread_ts=1688053280.871929&cid=C049MBCEW06) I downgraded to **openjdk 17.0.1** and now I'm able to run **nf-test v 0.8.1** successfully. I'm not a huge Java guy, so I'm not sure what the differences are between these major versions, but it might be useful to describe supported Java versions in the install documentation.

**Comment by GallVp** [comment]
Thank you for hint @BrianSanderson 

I also got around this issue by downgrading to openjdk@17 on Apple M1/macos 14.1.1 (23B81) using homebrew.

**Comment by lukfor** [comment]
Thanks for reporting this! Java 20 and 21 support is implemented in #171 and is available in the next release.
