### ISSUE TITLE
Repeated 'permission denied' when running `nf-test clean` or `rm -rf .nf-test`

### ISSUE THREAD

**Issue by jfy133** [askimed/nf-test#195]
I've come across an issue where I repeatedly am unable to remove the `.nf-test/` directory that is created after running `nf-test test`.

e.g. 

```
$ nf-test clean

🚀 nf-test 0.8.4
https://code.askimed.com/nf-test
(c) 2021 - 2024 Lukas Forer and Sebastian Schoenherr

java.nio.file.AccessDeniedException: /home/james/git/jfy133/nf-core-modules/.nf-test/tests/2de1503c64e99b820c9558bc8651f597/work/9a/cdce5df7c6f564bb5fc6589af2130f/test_files/build``` 

I also get this soemtimes when running `nf-test test`.

```$ nf-test test --tag blah --profile docker --verbose --debug

🚀 nf-test 0.8.4
https://code.askimed.com/nf-test
(c) 2021 - 2024 Lukas Forer and Sebastian Schoenherr

Found 1 files in test directory.
Error: java.io.IOException: Launch Directory '/home/james/git/jfy133/nf-core-modules/.nf-test/tests/7c72845fafd1a5f72d876ae1f228d73a' could not be deleted or created:
java.nio.file.AccessDeniedException: /home/james/git/jfy133/nf-core-modules/.nf-test/tests/7c72845fafd1a5f72d876ae1f228d73a/work/bf/670c3ca5bbedb5181e0db859e9fae9/test_files/build
java.io.IOException: Launch Directory '/home/james/git/jfy133/nf-core-modules/.nf-test/tests/7c72845fafd1a5f72d876ae1f228d73a' could not be deleted or created:
java.nio.file.AccessDeniedException: /home/james/git/jfy133/nf-core-modules/.nf-test/tests/7c72845fafd1a5f72d876ae1f228d73a/work/bf/670c3ca5bbedb5181e0db859e9fae9/test_files/build
        at com.askimed.nf.test.core.AbstractTest.initDirectory(AbstractTest.java:149)
        at com.askimed.nf.test.core.AbstractTest.setup(AbstractTest.java:105)
        at com.askimed.nf.test.core.AbstractTestSuite.evalualteTestClosures(AbstractTestSuite.java:85)
        at com.askimed.nf.test.lang.TestSuiteBuilder.parse(TestSuiteBuilder.java:116)
        at com.askimed.nf.test.core.TestExecutionEngine.parse(TestExecutionEngine.java:118)
        at com.askimed.nf.test.core.TestExecutionEngine.execute(TestExecutionEngine.java:159)
        at com.askimed.nf.test.commands.RunTestsCommand.execute(RunTestsCommand.java:184)
        at com.askimed.nf.test.commands.AbstractCommand.call(AbstractCommand.java:43)
        at com.askimed.nf.test.commands.AbstractCommand.call(AbstractCommand.java:18)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at com.askimed.nf.test.App.run(App.java:44)
        at com.askimed.nf.test.App.main(App.java:51)
  ```
  
  Unfortunately I've not be able to identify a pattern yet, other than it is when a test fails (for various reasons) or I cancel a test early, and I try to run nf-test again...

**Comment by jfy133** [comment]
Note I've installed nf-test via (bio)conda

**Comment by jfy133** [comment]
Ok I'm running on gitpod and I'm not having that issue at all... I guess it must be something to do with my installation, sorry!
