### ISSUE TITLE
Bug Report: PluginTest Failure

### ISSUE THREAD

**Issue by aaron-fishman-achillestx** [askimed/nf-test#44]
Hi nf-test, (@lukfor @seppinho )

Having an issue getting `mvn install` and `mvn test` to run without errors on the latest version. The new `PluginsTest` fails due to a missing class property: 
`groovy.lang.MissingPropertyException: No such property: fasta for class: sun.nio.fs.UnixPath`

However, if I run `mvn test -Dtest="PluginsTest"` the test passes just fine! 

I have attached the surefire report for your reference.

Is this the sort of error you have seen before?

Many thanks in advance,
Aaron

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report-3.0.xsd" version="3.0" name="com.askimed.nf.test.plugins.PluginsTest" time="23.353" tests="1" errors="0" skipped="0" failures="1">
  <properties>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="java.specification.version" value="11"/>
    <property name="sun.cpu.isalist" value=""/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.class.path" value="/home/a.fishman/repos/nf-test/target/test-classes:/home/a.fishman/repos/nf-test/target/classes:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy/3.0.9/groovy-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-ant/3.0.9/groovy-ant-3.0.9.jar:/home/a.fishman/.m2/repository/org/apache/ant/ant/1.10.11/ant-1.10.11.jar:/home/a.fishman/.m2/repository/org/apache/ant/ant-junit/1.10.11/ant-junit-1.10.11.jar:/home/a.fishman/.m2/repository/org/apache/ant/ant-launcher/1.10.11/ant-launcher-1.10.11.jar:/home/a.fishman/.m2/repository/org/apache/ant/ant-antlr/1.10.11/ant-antlr-1.10.11.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-astbuilder/3.0.9/groovy-astbuilder-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-cli-picocli/3.0.9/groovy-cli-picocli-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-console/3.0.9/groovy-console-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-datetime/3.0.9/groovy-datetime-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-docgenerator/3.0.9/groovy-docgenerator-3.0.9.jar:/home/a.fishman/.m2/repository/com/thoughtworks/qdox/qdox/1.12.1/qdox-1.12.1.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-groovydoc/3.0.9/groovy-groovydoc-3.0.9.jar:/home/a.fishman/.m2/repository/com/github/javaparser/javaparser-core/3.23.0/javaparser-core-3.23.0.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-groovysh/3.0.9/groovy-groovysh-3.0.9.jar:/home/a.fishman/.m2/repository/jline/jline/2.14.6/jline-2.14.6.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-jmx/3.0.9/groovy-jmx-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-json/3.0.9/groovy-json-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-jsr223/3.0.9/groovy-jsr223-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-macro/3.0.9/groovy-macro-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-servlet/3.0.9/groovy-servlet-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-sql/3.0.9/groovy-sql-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-swing/3.0.9/groovy-swing-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-templates/3.0.9/groovy-templates-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-test/3.0.9/groovy-test-3.0.9.jar:/home/a.fishman/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/a.fishman/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-test-junit5/3.0.9/groovy-test-junit5-3.0.9.jar:/home/a.fishman/.m2/repository/org/junit/platform/junit-platform-launcher/1.7.2/junit-platform-launcher-1.7.2.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-testng/3.0.9/groovy-testng-3.0.9.jar:/home/a.fishman/.m2/repository/org/testng/testng/7.4.0/testng-7.4.0.jar:/home/a.fishman/.m2/repository/com/beust/jcommander/1.78/jcommander-1.78.jar:/home/a.fishman/.m2/repository/org/webjars/jquery/3.5.1/jquery-3.5.1.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-xml/3.0.9/groovy-xml-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-nio/3.0.9/groovy-nio-3.0.9.jar:/home/a.fishman/.m2/repository/org/apache/ivy/ivy/2.5.0/ivy-2.5.0.jar:/home/a.fishman/.m2/repository/info/picocli/picocli/4.6.1/picocli-4.6.1.jar:/home/a.fishman/.m2/repository/com/opencsv/opencsv/5.5.2/opencsv-5.5.2.jar:/home/a.fishman/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar:/home/a.fishman/.m2/repository/org/apache/commons/commons-text/1.9/commons-text-1.9.jar:/home/a.fishman/.m2/repository/commons-beanutils/commons-beanutils/1.9.4/commons-beanutils-1.9.4.jar:/home/a.fishman/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/home/a.fishman/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar:/home/a.fishman/.m2/repository/org/apache/commons/commons-collections4/4.4/commons-collections4-4.4.jar:/home/a.fishman/.m2/repository/org/tap4j/tap4j/4.4.2/tap4j-4.4.2.jar:/home/a.fishman/.m2/repository/org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar:/home/a.fishman/.m2/repository/org/junit/jupiter/junit-jupiter/5.9.1/junit-jupiter-5.9.1.jar:/home/a.fishman/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.9.1/junit-jupiter-api-5.9.1.jar:/home/a.fishman/.m2/repository/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar:/home/a.fishman/.m2/repository/org/junit/platform/junit-platform-commons/1.9.1/junit-platform-commons-1.9.1.jar:/home/a.fishman/.m2/repository/org/apiguardian/apiguardian-api/1.1.2/apiguardian-api-1.1.2.jar:/home/a.fishman/.m2/repository/org/junit/jupiter/junit-jupiter-params/5.9.1/junit-jupiter-params-5.9.1.jar:/home/a.fishman/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.9.1/junit-jupiter-engine-5.9.1.jar:/home/a.fishman/.m2/repository/org/junit/platform/junit-platform-engine/1.9.1/junit-platform-engine-1.9.1.jar:"/>
    <property name="java.vm.vendor" value="JetBrains s.r.o."/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.vendor.url" value="https://openjdk.java.net/"/>
    <property name="user.timezone" value="UTC"/>
    <property name="java.vm.specification.version" value="11"/>
    <property name="os.name" value="Linux"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="user.country" value="GB"/>
    <property name="sun.boot.library.path" value="/home/a.fishman/miniconda3/lib"/>
    <property name="sun.java.command" value="/home/a.fishman/repos/nf-test/target/surefire/surefirebooter10111723401678877503.jar /home/a.fishman/repos/nf-test/target/surefire 2022-11-01T12-01-16_116-jvmRun1 surefire4671726568315671952tmp surefire_011115813422572361704tmp"/>
    <property name="jdk.debug" value="release"/>
    <property name="surefire.test.class.path" value="/home/a.fishman/repos/nf-test/target/test-classes:/home/a.fishman/repos/nf-test/target/classes:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy/3.0.9/groovy-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-ant/3.0.9/groovy-ant-3.0.9.jar:/home/a.fishman/.m2/repository/org/apache/ant/ant/1.10.11/ant-1.10.11.jar:/home/a.fishman/.m2/repository/org/apache/ant/ant-junit/1.10.11/ant-junit-1.10.11.jar:/home/a.fishman/.m2/repository/org/apache/ant/ant-launcher/1.10.11/ant-launcher-1.10.11.jar:/home/a.fishman/.m2/repository/org/apache/ant/ant-antlr/1.10.11/ant-antlr-1.10.11.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-astbuilder/3.0.9/groovy-astbuilder-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-cli-picocli/3.0.9/groovy-cli-picocli-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-console/3.0.9/groovy-console-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-datetime/3.0.9/groovy-datetime-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-docgenerator/3.0.9/groovy-docgenerator-3.0.9.jar:/home/a.fishman/.m2/repository/com/thoughtworks/qdox/qdox/1.12.1/qdox-1.12.1.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-groovydoc/3.0.9/groovy-groovydoc-3.0.9.jar:/home/a.fishman/.m2/repository/com/github/javaparser/javaparser-core/3.23.0/javaparser-core-3.23.0.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-groovysh/3.0.9/groovy-groovysh-3.0.9.jar:/home/a.fishman/.m2/repository/jline/jline/2.14.6/jline-2.14.6.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-jmx/3.0.9/groovy-jmx-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-json/3.0.9/groovy-json-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-jsr223/3.0.9/groovy-jsr223-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-macro/3.0.9/groovy-macro-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-servlet/3.0.9/groovy-servlet-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-sql/3.0.9/groovy-sql-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-swing/3.0.9/groovy-swing-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-templates/3.0.9/groovy-templates-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-test/3.0.9/groovy-test-3.0.9.jar:/home/a.fishman/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/a.fishman/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-test-junit5/3.0.9/groovy-test-junit5-3.0.9.jar:/home/a.fishman/.m2/repository/org/junit/platform/junit-platform-launcher/1.7.2/junit-platform-launcher-1.7.2.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-testng/3.0.9/groovy-testng-3.0.9.jar:/home/a.fishman/.m2/repository/org/testng/testng/7.4.0/testng-7.4.0.jar:/home/a.fishman/.m2/repository/com/beust/jcommander/1.78/jcommander-1.78.jar:/home/a.fishman/.m2/repository/org/webjars/jquery/3.5.1/jquery-3.5.1.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-xml/3.0.9/groovy-xml-3.0.9.jar:/home/a.fishman/.m2/repository/org/codehaus/groovy/groovy-nio/3.0.9/groovy-nio-3.0.9.jar:/home/a.fishman/.m2/repository/org/apache/ivy/ivy/2.5.0/ivy-2.5.0.jar:/home/a.fishman/.m2/repository/info/picocli/picocli/4.6.1/picocli-4.6.1.jar:/home/a.fishman/.m2/repository/com/opencsv/opencsv/5.5.2/opencsv-5.5.2.jar:/home/a.fishman/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar:/home/a.fishman/.m2/repository/org/apache/commons/commons-text/1.9/commons-text-1.9.jar:/home/a.fishman/.m2/repository/commons-beanutils/commons-beanutils/1.9.4/commons-beanutils-1.9.4.jar:/home/a.fishman/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/home/a.fishman/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar:/home/a.fishman/.m2/repository/org/apache/commons/commons-collections4/4.4/commons-collections4-4.4.jar:/home/a.fishman/.m2/repository/org/tap4j/tap4j/4.4.2/tap4j-4.4.2.jar:/home/a.fishman/.m2/repository/org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar:/home/a.fishman/.m2/repository/org/junit/jupiter/junit-jupiter/5.9.1/junit-jupiter-5.9.1.jar:/home/a.fishman/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.9.1/junit-jupiter-api-5.9.1.jar:/home/a.fishman/.m2/repository/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar:/home/a.fishman/.m2/repository/org/junit/platform/junit-platform-commons/1.9.1/junit-platform-commons-1.9.1.jar:/home/a.fishman/.m2/repository/org/apiguardian/apiguardian-api/1.1.2/apiguardian-api-1.1.2.jar:/home/a.fishman/.m2/repository/org/junit/jupiter/junit-jupiter-params/5.9.1/junit-jupiter-params-5.9.1.jar:/home/a.fishman/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.9.1/junit-jupiter-engine-5.9.1.jar:/home/a.fishman/.m2/repository/org/junit/platform/junit-platform-engine/1.9.1/junit-platform-engine-1.9.1.jar:"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="user.home" value="/home/a.fishman"/>
    <property name="user.language" value="en"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="java.version.date" value="2021-10-19"/>
    <property name="java.home" value="/home/a.fishman/miniconda3"/>
    <property name="file.separator" value="/"/>
    <property name="basedir" value="/home/a.fishman/repos/nf-test"/>
    <property name="java.vm.compressedOopsMode" value="Zero based"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="surefire.real.class.path" value="/home/a.fishman/repos/nf-test/target/surefire/surefirebooter10111723401678877503.jar"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="java.runtime.version" value="11.0.13+7-b1751.21"/>
    <property name="user.name" value="a.fishman"/>
    <property name="path.separator" value=":"/>
    <property name="os.version" value="3.10.0-957.21.3.el7.x86_64"/>
    <property name="java.runtime.name" value="OpenJDK Runtime Environment"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.vm.name" value="OpenJDK 64-Bit Server VM"/>
    <property name="java.vendor.version" value="JBR-11.0.13.7-1751.21-jcef"/>
    <property name="localRepository" value="/home/a.fishman/.m2/repository"/>
    <property name="java.vendor.url.bug" value="https://bugreport.java.com/bugreport/"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="java.version" value="11.0.13"/>
    <property name="user.dir" value="/home/a.fishman/repos/nf-test"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="java.library.path" value="/opt/clusterware/opt/genders/lib:/opt/clusterware/opt/ruby/lib:/opt/clusterware/opt/gridscheduler/lib/linux-x64:/opt/clusterware/opt/ruby/lib::/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.vendor" value="JetBrains s.r.o."/>
    <property name="java.vm.version" value="11.0.13+7-b1751.21"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="java.class.version" value="55.0"/>
  </properties>
  <testcase name="testScriptInConfig" classname="com.askimed.nf.test.plugins.PluginsTest" time="23.349">
    <failure message="expected: &lt;0&gt; but was: &lt;1&gt;" type="org.opentest4j.AssertionFailedError"><![CDATA[org.opentest4j.AssertionFailedError: expected: <0> but was: <1>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
	at com.askimed.nf.test.plugins.PluginsTest.testScriptInConfig(PluginsTest.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:223)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:139)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]></failure>
    <system-out><![CDATA[
🚀 nf-test 0.7.0
https://code.askimed.com/nf-test
(c) 2021 - 2022 Lukas Forer and Sebastian Schoenherr

Load .nf-test/plugins/nft-fasta/1.0.0/nft-fasta-1.0.0.jar
Load .nf-test/plugins/nft-fasta-2/2.0.0/nft-fasta-2-2.0.0.jar

Test COPY_FASTA

  Test [7c08cd80] 'Should work with fasta' Hello FASTA
FAILED (4.523s)

  groovy.lang.MissingPropertyException: No such property: fasta for class: sun.nio.fs.UnixPath
  Nextflow stdout:
  
  Nextflow stderr:
  
  

  Test [8bd203a5] 'Should work with fasta.gz' FAILED (4.356s)

  groovy.lang.MissingPropertyException: No such property: fasta for class: sun.nio.fs.UnixPath
  Nextflow stdout:
  
  Nextflow stderr:
  
  

  Test [59927fad] 'Should work with fasta.gz and fasta' FAILED (4.384s)

  groovy.lang.MissingPropertyException: No such property: fasta for class: sun.nio.fs.UnixPath
  Nextflow stdout:
  
  Nextflow stderr:
  
  

  Test [4878b52a] 'Should work with neq' FAILED (4.423s)

  groovy.lang.MissingPropertyException: No such property: fasta for class: sun.nio.fs.UnixPath
  Nextflow stdout:
  
  Nextflow stderr:
  
  

  Test [69cd9010] 'Sample seq1 should be in fasta.1' FAILED (4.325s)

  groovy.lang.MissingPropertyException: No such property: fasta for class: sun.nio.fs.UnixPath
  Nextflow stdout:
  
  Nextflow stderr:
  
  



FAILURE: Executed 5 tests in 22.017s (5 failed)

]]></system-out>
  </testcase>
</testsuite>%         
```

**Comment by lukfor** [comment]
Thanks for reporting this issue. The CI on GitHub executed the testcases in a different order therefore we didn't spot this issue. The problem is now fixed in main branch.

**Comment by aaron-fishman-achillestx** [comment]
Awesome - just tested this and happy to confirm the tests are passing now. Thanks for the fix!
