### ISSUE TITLE
Running fails with `com/askimed/nf/test/App has been compiled by a more recent version of the Java Runtime`

### ISSUE THREAD

**Issue by robsyme** [askimed/nf-test#5]
Hi askimed team

I'm very excited to try out the nf-test tool, but installing with 

```bash
curl -fsSL https://code.askimed.com/install/nf-test | bash
```

and then running with

```bash
./nf-test
```

Gives the error

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/askimed/nf/test/App has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

I'm using:

```
bash-4.2$ java -version
java version "1.8.0_72-ea"
Java(TM) SE Runtime Environment (build 1.8.0_72-ea-b05)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b05, mixed mode)
bash-4.2$ javac -version
javac 1.8.0_72-ea
```

Which version of java was used to compille nf-test, and is openjdk 1.8 not supported?

**Comment by lukfor** [comment]
Thank you for your feedback! nf-test 0.5.1 supports now Java 8.

**Comment by robsyme** [comment]
Thanks Lukas! Looking forward to adding (much needed) testing to our workflows.
